// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz_WebApp.Models;

namespace Quiz_WebApp.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20210408175249_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quiz_WebApp.Models.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OptionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            OptionId = 1,
                            OptionText = "Athens Games (1896)",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 2,
                            OptionText = "London Games (1908)",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 3,
                            OptionText = "Paris Games (1924)",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 4,
                            OptionText = "Amsterdam Games (1928)",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 5,
                            OptionText = "unity among various nations of the world",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 6,
                            OptionText = "speed, perfection and strength",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 7,
                            OptionText = "sports as a means for securing harmony among nations",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 8,
                            OptionText = "continuity between the ancient and modern games",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 9,
                            OptionText = "saponification",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 10,
                            OptionText = "hydrogenation",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 11,
                            OptionText = "fermentation",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 12,
                            OptionText = "hydrolysis",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 13,
                            OptionText = "Alexander Fleming",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 14,
                            OptionText = "Albert Einstein",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 15,
                            OptionText = "Archimeder",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 16,
                            OptionText = "Aryabhatta",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 17,
                            OptionText = "200",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 18,
                            OptionText = "206",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 19,
                            OptionText = "212",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 20,
                            OptionText = "218",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 21,
                            OptionText = "studying population dynamics",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 22,
                            OptionText = "collecting population data",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 23,
                            OptionText = "evolving population policies, family planning and related programmes",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 24,
                            OptionText = "All of the above",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 25,
                            OptionText = "largest railway station",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 26,
                            OptionText = "highest railway station",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 27,
                            OptionText = "longest railway station",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 28,
                            OptionText = "None of the above",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 29,
                            OptionText = "Behavior of human beings",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 30,
                            OptionText = "Insects",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 31,
                            OptionText = "The origin and history of technical and scientific terms",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 32,
                            OptionText = "The formation of rocks",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 33,
                            OptionText = "Asia",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 34,
                            OptionText = "Africa",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 35,
                            OptionText = "Europe",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 36,
                            OptionText = "Australia",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 37,
                            OptionText = "Physics and Chemistry",
                            QuestionId = 10
                        },
                        new
                        {
                            OptionId = 38,
                            OptionText = "Physiology or Medicine",
                            QuestionId = 10
                        },
                        new
                        {
                            OptionId = 39,
                            OptionText = "Literature, Peace and Economics",
                            QuestionId = 10
                        },
                        new
                        {
                            OptionId = 40,
                            OptionText = "All of the above",
                            QuestionId = 10
                        },
                        new
                        {
                            OptionId = 41,
                            OptionText = "Labour Party",
                            QuestionId = 11
                        },
                        new
                        {
                            OptionId = 42,
                            OptionText = "Nazi Party",
                            QuestionId = 11
                        },
                        new
                        {
                            OptionId = 43,
                            OptionText = "Ku-Klux-Klan",
                            QuestionId = 11
                        },
                        new
                        {
                            OptionId = 44,
                            OptionText = "Democratic Party",
                            QuestionId = 11
                        },
                        new
                        {
                            OptionId = 45,
                            OptionText = "1914",
                            QuestionId = 12
                        },
                        new
                        {
                            OptionId = 46,
                            OptionText = "1915",
                            QuestionId = 12
                        },
                        new
                        {
                            OptionId = 47,
                            OptionText = "1916",
                            QuestionId = 12
                        },
                        new
                        {
                            OptionId = 48,
                            OptionText = "1917",
                            QuestionId = 12
                        },
                        new
                        {
                            OptionId = 49,
                            OptionText = "International Civil Aviation Organization",
                            QuestionId = 13
                        },
                        new
                        {
                            OptionId = 50,
                            OptionText = "Indian Corporation of Agriculture Organization",
                            QuestionId = 13
                        },
                        new
                        {
                            OptionId = 51,
                            OptionText = "Institute of Company of Accounts Organization",
                            QuestionId = 13
                        },
                        new
                        {
                            OptionId = 52,
                            OptionText = "None of the above",
                            QuestionId = 13
                        },
                        new
                        {
                            OptionId = 53,
                            OptionText = "gold",
                            QuestionId = 14
                        },
                        new
                        {
                            OptionId = 54,
                            OptionText = "copper",
                            QuestionId = 14
                        },
                        new
                        {
                            OptionId = 55,
                            OptionText = "mica",
                            QuestionId = 14
                        },
                        new
                        {
                            OptionId = 56,
                            OptionText = "None of the above",
                            QuestionId = 14
                        },
                        new
                        {
                            OptionId = 57,
                            OptionText = "Horse racing",
                            QuestionId = 15
                        },
                        new
                        {
                            OptionId = 58,
                            OptionText = "Polo",
                            QuestionId = 15
                        },
                        new
                        {
                            OptionId = 59,
                            OptionText = "Shooting",
                            QuestionId = 15
                        },
                        new
                        {
                            OptionId = 60,
                            OptionText = "Snooker",
                            QuestionId = 15
                        },
                        new
                        {
                            OptionId = 61,
                            OptionText = "1967",
                            QuestionId = 16
                        },
                        new
                        {
                            OptionId = 62,
                            OptionText = "1968",
                            QuestionId = 16
                        },
                        new
                        {
                            OptionId = 63,
                            OptionText = "1958",
                            QuestionId = 16
                        },
                        new
                        {
                            OptionId = 64,
                            OptionText = "1922",
                            QuestionId = 16
                        },
                        new
                        {
                            OptionId = 65,
                            OptionText = "developed the telescope",
                            QuestionId = 17
                        },
                        new
                        {
                            OptionId = 66,
                            OptionText = "discovered four satellites of Jupiter",
                            QuestionId = 17
                        },
                        new
                        {
                            OptionId = 67,
                            OptionText = "discovered that the movement of pendulum produces a regular time measurement",
                            QuestionId = 17
                        },
                        new
                        {
                            OptionId = 68,
                            OptionText = "All of the above",
                            QuestionId = 17
                        },
                        new
                        {
                            OptionId = 69,
                            OptionText = "the infrared light kills bacteria in the body",
                            QuestionId = 18
                        },
                        new
                        {
                            OptionId = 70,
                            OptionText = "resistance power increases",
                            QuestionId = 18
                        },
                        new
                        {
                            OptionId = 71,
                            OptionText = "the pigment cells in the skin get stimulated and produce a healthy tan",
                            QuestionId = 18
                        },
                        new
                        {
                            OptionId = 72,
                            OptionText = "the ultraviolet rays convert skin oil into Vitamin D",
                            QuestionId = 18
                        },
                        new
                        {
                            OptionId = 73,
                            OptionText = "Letter of Credit (L/C)",
                            QuestionId = 19
                        },
                        new
                        {
                            OptionId = 74,
                            OptionText = "laissezfaire",
                            QuestionId = 19
                        },
                        new
                        {
                            OptionId = 75,
                            OptionText = "inflation",
                            QuestionId = 19
                        },
                        new
                        {
                            OptionId = 76,
                            OptionText = "None of the above",
                            QuestionId = 19
                        },
                        new
                        {
                            OptionId = 77,
                            OptionText = "sliding to rolling",
                            QuestionId = 20
                        },
                        new
                        {
                            OptionId = 78,
                            OptionText = "rolling to sliding",
                            QuestionId = 20
                        },
                        new
                        {
                            OptionId = 79,
                            OptionText = "potential energy to kinetic energy",
                            QuestionId = 20
                        },
                        new
                        {
                            OptionId = 80,
                            OptionText = "dynamic to static",
                            QuestionId = 20
                        });
                });

            modelBuilder.Entity("Quiz_WebApp.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            CorrectAnswer = 4,
                            QuestionText = "The Olympic Flame, was, for the first time, ceremonially lighted and burnt in a giant torch at the entrance of the stadium at"
                        },
                        new
                        {
                            QuestionId = 2,
                            CorrectAnswer = 8,
                            QuestionText = "The Olympic Flame symbolises"
                        },
                        new
                        {
                            QuestionId = 3,
                            CorrectAnswer = 11,
                            QuestionText = "The reaction which converts sugar solution into alcohol is an example of"
                        },
                        new
                        {
                            QuestionId = 4,
                            CorrectAnswer = 13,
                            QuestionText = "The Scottish bacteriologist who discovered penicillin was"
                        },
                        new
                        {
                            QuestionId = 5,
                            CorrectAnswer = 18,
                            QuestionText = "The number of already named bones in the human skeleton is"
                        },
                        new
                        {
                            QuestionId = 6,
                            CorrectAnswer = 24,
                            QuestionText = "The purpose of United Nations Fund for Population Activities (UNFPA) is"
                        },
                        new
                        {
                            QuestionId = 7,
                            CorrectAnswer = 25,
                            QuestionText = "Grand Central Terminal, Park Avenue, New York is the world's"
                        },
                        new
                        {
                            QuestionId = 8,
                            CorrectAnswer = 30,
                            QuestionText = "Entomology is the science that studies"
                        },
                        new
                        {
                            QuestionId = 9,
                            CorrectAnswer = 34,
                            QuestionText = "Eritrea, which became the 182nd member of the UN in 1993, is in the continent of"
                        },
                        new
                        {
                            QuestionId = 10,
                            CorrectAnswer = 40,
                            QuestionText = "For which of the following disciplines is Nobel Prize awarded?"
                        },
                        new
                        {
                            QuestionId = 11,
                            CorrectAnswer = 42,
                            QuestionText = "Hitler party which came into power in 1933 is known as"
                        },
                        new
                        {
                            QuestionId = 12,
                            CorrectAnswer = 45,
                            QuestionText = "In which year of First World War Germany declared war on Russia and France?"
                        },
                        new
                        {
                            QuestionId = 13,
                            CorrectAnswer = 49,
                            QuestionText = "ICAO stands for"
                        },
                        new
                        {
                            QuestionId = 14,
                            CorrectAnswer = 55,
                            QuestionText = "India has largest deposits of ____ in the world."
                        },
                        new
                        {
                            QuestionId = 15,
                            CorrectAnswer = 57,
                            QuestionText = "Epsom (England) is the place associated with"
                        },
                        new
                        {
                            QuestionId = 16,
                            CorrectAnswer = 61,
                            QuestionText = "First human heart transplant operation conducted by Dr. Christiaan Barnard on Louis Washkansky, was conducted in"
                        },
                        new
                        {
                            QuestionId = 17,
                            CorrectAnswer = 68,
                            QuestionText = "Galileo was an Italian astronomer who"
                        },
                        new
                        {
                            QuestionId = 18,
                            CorrectAnswer = 72,
                            QuestionText = "Exposure to sunlight helps a person improve his health because"
                        },
                        new
                        {
                            QuestionId = 19,
                            CorrectAnswer = 73,
                            QuestionText = "Guarantee to an exporter that the importer of his goods will pay immediately for the goods ordered by him, is known as"
                        },
                        new
                        {
                            QuestionId = 20,
                            CorrectAnswer = 77,
                            QuestionText = "Friction can be reduced by changing from"
                        });
                });

            modelBuilder.Entity("Quiz_WebApp.Models.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("QuizDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("QuizId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Quiz_WebApp.Models.Option", b =>
                {
                    b.HasOne("Quiz_WebApp.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });
#pragma warning restore 612, 618
        }
    }
}
